"""Proof that our own binding answers exactly what pyswisseph answered.

Two halves, and the first one runs TODAY while the second waits for a library:

1. The CONSTANTS are checked against pyswisseph right now. A wrong literal in `app/engine/swe.py` does not
   raise anything - `FLG_SIDEREAL` off by one bit returns tropical longitudes, which are ordinary-looking
   numbers about 24 degrees wrong - so this is the check that earns its place immediately.
2. The PRIMITIVES are compared against `tests/fixtures/swe_golden.json`, which was generated by pyswisseph
   before the swap (see scripts/build_swe_golden.py). This half skips while libswe is not built, and says
   so rather than passing quietly: a proof that silently does not run is worse than no proof.
"""

import json
import pathlib

import pytest

from app.engine import swe

GOLDEN = pathlib.Path(__file__).parent / "fixtures/swe_golden.json"
# 0.001 arcsecond, the tolerance the spec asks for, in degrees.
ARCSEC = 1.0 / 3600.0
TOLERANCE = 0.001 * ARCSEC


def test_every_constant_matches_the_library_we_are_replacing():
    """Pins the literals in app/engine/swe.py to pyswisseph's own values while we still have it."""
    pyswisseph = pytest.importorskip("swisseph", reason="pyswisseph removed; constants already pinned")
    for name in ("FLG_SWIEPH", "FLG_SPEED", "FLG_SIDEREAL", "SIDM_LAHIRI", "CALC_RISE",
                 "BIT_HINDU_RISING", "SUN", "MOON", "MARS", "MERCURY", "JUPITER", "VENUS",
                 "SATURN", "MEAN_NODE"):
        assert getattr(swe, name) == getattr(pyswisseph, name), name


def test_the_golden_fixture_was_made_by_pyswisseph_and_not_by_us():
    """The fixture's value is that the library being REPLACED wrote it. If this ever says otherwise, the
    file has been regenerated with the new binding and proves nothing at all."""
    data = json.loads(GOLDEN.read_text(encoding="utf-8"))
    assert data["generated_by"] == "pyswisseph"
    assert data["pyswisseph_libswe_version"] == "2.10.03", "equivalence is only meaningful per libswe version"
    assert len(data["rows"]) >= 200


def test_the_fixture_carries_no_real_person():
    """tests/ is published. The generated charts are coordinates and Julian days only - no name, no place."""
    text = GOLDEN.read_text(encoding="utf-8")
    for forbidden in ("name", "place", "city", "Miraj"):
        assert forbidden not in text.replace('"note"', ""), forbidden


@pytest.mark.skipif(not swe.available(), reason="libswe is not built here; see deploy/build-libswe.sh")
def test_our_binding_reproduces_pyswisseph_to_a_thousandth_of_an_arcsecond():
    """The whole point of Part 1. Every primitive, on 200 invented charts across 1900-2100."""
    data = json.loads(GOLDEN.read_text(encoding="utf-8"))
    swe.set_ephe_path(str(pathlib.Path(__file__).resolve().parents[1] / "app/engine/ephe"))
    swe.set_sid_mode(swe.SIDM_LAHIRI)
    flags = swe.FLG_SWIEPH | swe.FLG_SIDEREAL | swe.FLG_SPEED
    bodies = {"Sun": swe.SUN, "Moon": swe.MOON, "Mars": swe.MARS, "Mercury": swe.MERCURY,
              "Jupiter": swe.JUPITER, "Venus": swe.VENUS, "Saturn": swe.SATURN, "Rahu": swe.MEAN_NODE}
    for row in data["rows"]:
        jd, lat, lon = row["jd"], row["lat"], row["lon"]
        for graha, (longitude, speed) in row["grahas"].items():
            values, _ = swe.calc_ut(jd, bodies[graha], flags)
            assert abs(values[0] - longitude) < TOLERANCE, f"{graha} longitude at jd={jd}"
            assert abs(values[3] - speed) < TOLERANCE, f"{graha} speed at jd={jd}"
        assert abs(swe.get_ayanamsa_ut(jd) - row["ayanamsa"]) < TOLERANCE, f"ayanamsa at jd={jd}"
        _, ascmc = swe.houses_ex(jd, lat, lon, b"W", swe.FLG_SIDEREAL)
        assert abs(ascmc[0] - row["ascendant"]) < TOLERANCE, f"ascendant at jd={jd} lat={lat}"
        result, times = swe.rise_trans(jd, swe.SUN, swe.CALC_RISE | swe.BIT_HINDU_RISING,
                                       (lon, lat, 0.0), 0.0, 0.0, swe.FLG_SWIEPH)
        if row["sunrise"] is None:
            assert result != 0, f"expected no sunrise at lat={lat}, jd={jd}"
        else:
            assert result == 0 and abs(times[0] - row["sunrise"]) < TOLERANCE, f"sunrise at jd={jd}"


def _chart_and_timeline(birth, as_of):
    """A whole chart plus the 2026-2051 timeline: everything the books print, computed from the primitives."""
    from app.ai import engine_facts
    from app.ai.report import _chart

    chart = _chart(birth, as_of)
    return {"chart": chart, "facts": engine_facts.report_facts(chart, as_of)}


def test_every_derived_value_is_identical_too_including_the_transit_table(monkeypatch):
    """Nakshatra, pada, lagna, house cusps, D9, dasha dates and the 2026-2051 transit table.

    These are pure Python arithmetic on top of the six primitives, so in principle matching primitives is
    enough - but "in principle" is how a wrapper swap goes wrong, and this costs nothing to check. It runs
    the SAME chart twice, once through pyswisseph and once through our binding, and compares the whole
    structure as JSON.

    `app/engine/core.py` is NOT edited to do this: `core._swe()` returns the module-level name `swe`, so
    substituting `core.swe` is enough. The thread-local `configured` flag has to be cleared too, or the new
    library never gets its ephemeris path and sidereal mode set.
    """
    pytest.importorskip("swisseph", reason="needs pyswisseph to compare against")
    if not swe.available():
        pytest.skip("libswe is not built here; see deploy/build-libswe.sh")

    import json as _json

    from app.engine import core
    from tests import reference_charts
    from tests.test_pdf import AS_OF, _birth

    def measure():
        core._thread.configured = False
        out = {}
        for name in ("PRIMARY", "SECONDARY"):
            reference = getattr(reference_charts, name, None)
            if reference is None:
                continue
            out[name] = _chart_and_timeline(_birth(reference), AS_OF)
        return _json.dumps(out, sort_keys=True, default=str)

    with_pyswisseph = measure()          # the module as imported: pyswisseph
    monkeypatch.setattr(core, "swe", swe)
    with_our_binding = measure()
    core._thread.configured = False      # leave the process as we found it

    assert with_our_binding == with_pyswisseph, "a derived value differs between the two libraries"
    assert len(with_pyswisseph) > 10000, "guard: the comparison must not be trivially empty"
